language: scala

jdk: openjdk8

sudo: false

script:
  - rm project/plugins.sbt
  - rm appengine.sbt
  - sbt test

cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/launchers"

before_cache:
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
